server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.1.116:3306/ssm_crud?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
mybatis:
  type-aliases-package: com.ssm.crud.dao
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true